/***************************************************************************
 *
 * Copyright (c) 2010-2015 Petri Purho, Dennis Belfrage, Olli Harjola
 *
 * This software is provided 'as-is', without any express or implied
 * warranty.  In no event will the authors be held liable for any damages
 * arising from the use of this software.
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software. If you use this software
 *    in a product, an acknowledgment in the product documentation would be
 *    appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 *
 ***************************************************************************/

#ifndef INC_KEYBOARD_H
#define INC_KEYBOARD_H

#include <vector>
#include "libraries.h"
#include "poro_types.h"
#include "ikeyboard_listener.h"

namespace poro {

class Keyboard
{
public:
	Keyboard();
	~Keyboard() { }

	void AddKeyboardListener(IKeyboardListener* listener);
	void RemoveKeyboardListener(IKeyboardListener* listener);

	void OnFrameStart();

	void FireKeyDownEvent(int button, types::charset unicode);
	void FireKeyUpEvent(int button, types::charset unicode);

	bool IsKeyDown(int button) const;
	bool IsKeyJustDown(int button) const;
	bool IsKeyJustUp(int button) const;

	bool IsShiftDown() const;
	bool IsAltDown() const;
	bool IsCtrlDown() const;

	void SetDisableRepeats(bool disable_repeats);

private:
	void SetKeyDown(int button, bool down);

	std::vector< IKeyboardListener* > mListeners;

	std::vector< bool > mKeysDown;
	std::vector< bool > mKeysJustDown;
	std::vector< bool > mKeysJustUp;

	bool mDisableRepeats;
};

//-----------------------------------------------------------------------------

inline void Keyboard::SetDisableRepeats(bool disable_repeats) {
	mDisableRepeats = disable_repeats;
}

} // end of namespace poro

//-----------------------------------------------------------------------------

// #ifdef PORO_USE_SDL2
	#define PORO_SCANCODE_TO_KEYCODE(X)  (X + 100)

	enum
	{
	POROK_UNKNOWN = 0,

	POROK_RETURN = '\r',
	POROK_ESCAPE = '\033',
	POROK_BACKSPACE = '\b',
	POROK_TAB = '\t',
	POROK_SPACE = ' ',
	POROK_EXCLAIM = '!',
	POROK_QUOTEDBL = '"',
	POROK_HASH = '#',
	POROK_PERCENT = '%',
	POROK_DOLLAR = '$',
	POROK_AMPERSAND = '&',
	POROK_QUOTE = '\'',
	POROK_LEFTPAREN = '(',
	POROK_RIGHTPAREN = ')',
	POROK_ASTERISK = '*',
	POROK_PLUS = '+',
	POROK_COMMA = ',',
	POROK_MINUS = '-',
	POROK_PERIOD = '.',
	POROK_SLASH = '/',
	POROK_0 = '0',
	POROK_1 = '1',
	POROK_2 = '2',
	POROK_3 = '3',
	POROK_4 = '4',
	POROK_5 = '5',
	POROK_6 = '6',
	POROK_7 = '7',
	POROK_8 = '8',
	POROK_9 = '9',
	POROK_COLON = ':',
	POROK_SEMICOLON = ';',
	POROK_LESS = '<',
	POROK_EQUALS = '=',
	POROK_GREATER = '>',
	POROK_QUESTION = '?',
	POROK_AT = '@',
	/*
	Skip uppercase letters
	*/
	POROK_LEFTBRACKET = '[',
	POROK_BACKSLASH = '\\',
	POROK_RIGHTBRACKET = ']',
	POROK_CARET = '^',
	POROK_UNDERSCORE = '_',
	POROK_BACKQUOTE = '`',
	POROK_a = 'a',
	POROK_b = 'b',
	POROK_c = 'c',
	POROK_d = 'd',
	POROK_e = 'e',
	POROK_f = 'f',
	POROK_g = 'g',
	POROK_h = 'h',
	POROK_i = 'i',
	POROK_j = 'j',
	POROK_k = 'k',
	POROK_l = 'l',
	POROK_m = 'm',
	POROK_n = 'n',
	POROK_o = 'o',
	POROK_p = 'p',
	POROK_q = 'q',
	POROK_r = 'r',
	POROK_s = 's',
	POROK_t = 't',
	POROK_u = 'u',
	POROK_v = 'v',
	POROK_w = 'w',
	POROK_x = 'x',
	POROK_y = 'y',
	POROK_z = 'z',

	POROK_CAPSLOCK = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_CAPSLOCK ),

	POROK_F1 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F1 ),
	POROK_F2 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F2 ),
	POROK_F3 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F3 ),
	POROK_F4 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F4 ),
	POROK_F5 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F5 ),
	POROK_F6 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F6 ),
	POROK_F7 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F7 ),
	POROK_F8 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F8 ),
	POROK_F9 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F9 ),
	POROK_F10 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F10 ),
	POROK_F11 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F11 ),
	POROK_F12 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F12 ),

	POROK_PRINTSCREEN = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_PRINTSCREEN ),
	POROK_SCROLLLOCK = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_SCROLLLOCK ),
	POROK_PAUSE = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_PAUSE ),
	POROK_INSERT = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_INSERT ),
	POROK_HOME = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_HOME ),
	POROK_PAGEUP = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_PAGEUP ),
	POROK_DELETE = '\177',
	POROK_END = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_END ),
	POROK_PAGEDOWN = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_PAGEDOWN ),
	POROK_RIGHT = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_RIGHT ),
	POROK_LEFT = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_LEFT ),
	POROK_DOWN = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_DOWN ),
	POROK_UP = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_UP ),

	POROK_NUMLOCKCLEAR = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_NUMLOCKCLEAR ),
	POROK_KP_DIVIDE = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_DIVIDE ),
	POROK_KP_MULTIPLY = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_MULTIPLY ),
	POROK_KP_MINUS = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_MINUS ),
	POROK_KP_PLUS = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_PLUS ),
	POROK_KP_ENTER = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_ENTER ),
	POROK_KP_1 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_1 ),
	POROK_KP_2 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_2 ),
	POROK_KP_3 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_3 ),
	POROK_KP_4 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_4 ),
	POROK_KP_5 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_5 ),
	POROK_KP_6 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_6 ),
	POROK_KP_7 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_7 ),
	POROK_KP_8 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_8 ),
	POROK_KP_9 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_9 ),
	POROK_KP_0 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_0 ),
	POROK_KP_PERIOD = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_PERIOD ),

	POROK_APPLICATION = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_APPLICATION ),
	POROK_POWER = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_POWER ),
	POROK_KP_EQUALS = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_EQUALS ),
	POROK_F13 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F13 ),
	POROK_F14 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F14 ),
	POROK_F15 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F15 ),
	POROK_F16 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F16 ),
	POROK_F17 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F17 ),
	POROK_F18 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F18 ),
	POROK_F19 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F19 ),
	POROK_F20 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F20 ),
	POROK_F21 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F21 ),
	POROK_F22 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F22 ),
	POROK_F23 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F23 ),
	POROK_F24 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_F24 ),
	POROK_EXECUTE = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_EXECUTE ),
	POROK_HELP = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_HELP ),
	POROK_MENU = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_MENU ),
	POROK_SELECT = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_SELECT ),
	POROK_STOP = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_STOP ),
	POROK_AGAIN = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_AGAIN ),
	POROK_UNDO = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_UNDO ),
	POROK_CUT = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_CUT ),
	POROK_COPY = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_COPY ),
	POROK_PASTE = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_PASTE ),
	POROK_FIND = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_FIND ),
	POROK_MUTE = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_MUTE ),
	POROK_VOLUMEUP = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_VOLUMEUP ),
	POROK_VOLUMEDOWN = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_VOLUMEDOWN ),
	POROK_KP_COMMA = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_COMMA ),
	POROK_KP_EQUALSAS400 =
	PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_EQUALSAS400 ),

	POROK_ALTERASE = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_ALTERASE ),
	POROK_SYSREQ = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_SYSREQ ),
	POROK_CANCEL = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_CANCEL ),
	POROK_CLEAR = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_CLEAR ),
	POROK_PRIOR = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_PRIOR ),
	POROK_RETURN2 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_RETURN2 ),
	POROK_SEPARATOR = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_SEPARATOR ),
	POROK_OUT = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_OUT ),
	POROK_OPER = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_OPER ),
	POROK_CLEARAGAIN = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_CLEARAGAIN ),
	POROK_CRSEL = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_CRSEL ),
	POROK_EXSEL = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_EXSEL ),

	POROK_KP_00 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_00 ),
	POROK_KP_000 = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_000 ),
	POROK_THOUSANDSSEPARATOR =
	PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_THOUSANDSSEPARATOR ),
	POROK_DECIMALSEPARATOR =
	PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_DECIMALSEPARATOR ),
	POROK_CURRENCYUNIT = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_CURRENCYUNIT ),
	POROK_CURRENCYSUBUNIT =
	PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_CURRENCYSUBUNIT ),
	POROK_KP_LEFTPAREN = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_LEFTPAREN ),
	POROK_KP_RIGHTPAREN = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_RIGHTPAREN ),
	POROK_KP_LEFTBRACE = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_LEFTBRACE ),
	POROK_KP_RIGHTBRACE = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_RIGHTBRACE ),
	POROK_KP_TAB = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_TAB ),
	POROK_KP_BACKSPACE = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_BACKSPACE ),
	POROK_KP_A = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_A ),
	POROK_KP_B = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_B ),
	POROK_KP_C = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_C ),
	POROK_KP_D = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_D ),
	POROK_KP_E = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_E ),
	POROK_KP_F = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_F ),
	POROK_KP_XOR = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_XOR ),
	POROK_KP_POWER = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_POWER ),
	POROK_KP_PERCENT = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_PERCENT ),
	POROK_KP_LESS = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_LESS ),
	POROK_KP_GREATER = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_GREATER ),
	POROK_KP_AMPERSAND = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_AMPERSAND ),
	POROK_KP_DBLAMPERSAND =
	PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_DBLAMPERSAND ),
	POROK_KP_VERTICALBAR =
	PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_VERTICALBAR ),
	POROK_KP_DBLVERTICALBAR =
	PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_DBLVERTICALBAR ),
	POROK_KP_COLON = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_COLON ),
	POROK_KP_HASH = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_HASH ),
	POROK_KP_SPACE = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_SPACE ),
	POROK_KP_AT = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_AT ),
	POROK_KP_EXCLAM = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_EXCLAM ),
	POROK_KP_MEMSTORE = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_MEMSTORE ),
	POROK_KP_MEMRECALL = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_MEMRECALL ),
	POROK_KP_MEMCLEAR = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_MEMCLEAR ),
	POROK_KP_MEMADD = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_MEMADD ),
	POROK_KP_MEMSUBTRACT =
	PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_MEMSUBTRACT ),
	POROK_KP_MEMMULTIPLY =
	PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_MEMMULTIPLY ),
	POROK_KP_MEMDIVIDE = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_MEMDIVIDE ),
	POROK_KP_PLUSMINUS = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_PLUSMINUS ),
	POROK_KP_CLEAR = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_CLEAR ),
	POROK_KP_CLEARENTRY = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_CLEARENTRY ),
	POROK_KP_BINARY = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_BINARY ),
	POROK_KP_OCTAL = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_OCTAL ),
	POROK_KP_DECIMAL = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_DECIMAL ),
	POROK_KP_HEXADECIMAL =
	PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KP_HEXADECIMAL ),

	POROK_LCTRL = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_LCTRL ),
	POROK_LSHIFT = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_LSHIFT ),
	POROK_LALT = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_LALT ),
	POROK_LGUI = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_LGUI ),
	POROK_RCTRL = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_RCTRL ),
	POROK_RSHIFT = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_RSHIFT ),
	POROK_RALT = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_RALT ),
	POROK_RGUI = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_RGUI ),

	POROK_MODE = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_MODE ),

	POROK_AUDIONEXT = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_AUDIONEXT ),
	POROK_AUDIOPREV = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_AUDIOPREV ),
	POROK_AUDIOSTOP = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_AUDIOSTOP ),
	POROK_AUDIOPLAY = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_AUDIOPLAY ),
	POROK_AUDIOMUTE = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_AUDIOMUTE ),
	POROK_MEDIASELECT = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_MEDIASELECT ),
	POROK_WWW = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_WWW ),
	POROK_MAIL = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_MAIL ),
	POROK_CALCULATOR = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_CALCULATOR ),
	POROK_COMPUTER = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_COMPUTER ),
	POROK_AC_SEARCH = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_AC_SEARCH ),
	POROK_AC_HOME = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_AC_HOME ),
	POROK_AC_BACK = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_AC_BACK ),
	POROK_AC_FORWARD = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_AC_FORWARD ),
	POROK_AC_STOP = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_AC_STOP ),
	POROK_AC_REFRESH = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_AC_REFRESH ),
	POROK_AC_BOOKMARKS = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_AC_BOOKMARKS ),

	POROK_BRIGHTNESSDOWN =
	PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_BRIGHTNESSDOWN ),
	POROK_BRIGHTNESSUP = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_BRIGHTNESSUP ),
	POROK_DISPLAYSWITCH = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_DISPLAYSWITCH ),
	POROK_KBDILLUMTOGGLE =
	PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KBDILLUMTOGGLE ),
	POROK_KBDILLUMDOWN = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KBDILLUMDOWN ),
	POROK_KBDILLUMUP = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_KBDILLUMUP ),
	POROK_EJECT = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_EJECT ),
	POROK_SLEEP = PORO_SCANCODE_TO_KEYCODE( SDL_SCANCODE_SLEEP ),
	POROK_SPECIAL_COUNT = POROK_SLEEP + 1,
	};

#undef PORO_SCANCODE_TO_KEYCODE

	// #endif

//-----------------------------------------------------------------------------

#endif